#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path

from common import OVERRIDE_DIR, RECIPE_IDENTIFIER_PATTERN, expected_override_header


GENERATED_COMMENT = re.compile(r"^# (?:Generated by AutoPkg|Generated file)\.")
REFRESH_COMMENT = re.compile(r"^# Refresh with:")


def expected_text(path: Path) -> str:
    original = path.read_text(encoding="utf-8")
    match = RECIPE_IDENTIFIER_PATTERN.search(original)
    if not match:
        raise SystemExit(f"{path}: missing Identifier")
    identifier = match.group(1)

    lines = original.splitlines()
    if lines and lines[0] == "---":
        lines.pop(0)
    while lines and (GENERATED_COMMENT.match(lines[0]) or REFRESH_COMMENT.match(lines[0])):
        lines.pop(0)
    while lines and not lines[0]:
        lines.pop(0)
    return "\n".join([*expected_override_header(identifier), *lines]) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Mark generated AutoPkg overrides")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("paths", nargs="*", type=Path)
    arguments = parser.parse_args()

    paths = arguments.paths or sorted(OVERRIDE_DIR.glob("*.munki.recipe.yaml"))
    changed: list[Path] = []
    for path in paths:
        expected = expected_text(path)
        if path.read_text(encoding="utf-8") == expected:
            continue
        changed.append(path)
        if not arguments.check:
            path.write_text(expected, encoding="utf-8")

    if arguments.check and changed:
        for path in changed:
            print(path)
        print(f"{len(changed)} generated overrides need headers")
        return 1
    print(f"Marked {len(changed)} of {len(paths)} generated overrides")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
